### ISSUE TITLE
Does this work for EMQX Cloud?

### ISSUE THREAD

**Issue by adam-bentley** [emqx/emqx-exporter#29]
Hi,

I just wanted to know if this works with EMQX cloud.

Thanks.

**Comment by yang-yinbo** [comment]
It works fine if you have access to the EMQX API.

**Comment by suyu41** [comment]
For EMQX Cloud's Prometheus Monitoring Alerts reference:
https://docs.emqx.com/en/cloud/latest/deployments/prometheus.html
